apiVersion: apps/v1
kind: Deployment
metadata:
  name: iota
  namespace: security
spec:
  template:
    spec:
      containers:
        - name: iota
          env:
            - $patch: replace
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/969779760014/iota-cloudtrail-queue"
            - name: S3_BUCKET
              value: "iota-cloudtrail-969779760014-us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
            - name: DATA_LAKE_BUCKET
              value: ""
            - name: ENABLE_METRICS
              value: "true"
            - name: HEALTH_PORT
              value: "8080"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: iota-slack-webhook
                  key: webhook-url
                  optional: true
