CREDENTIAL_EXPOSURE_ACTIONS = {
    "appsync:ListApiKeys",
    "athena:GetSession",
    "codeartifact:GetAuthorizationToken",
    "codepipeline:PollForJobs",
    "cognito-identity:GetCredentialsForIdentity",
    "cognito-identity:GetOpenIdToken",
    "cognito-identity:GetOpenIdTokenForDeveloperIdentity",
    "cognito-idp:DescribeUserPoolClient",
    "cognito-idp:GetUserAttributeVerificationCode",
    "connect:GetFederationToken",
    "connect:ListSecurityKeys",
    "ec2:GetPasswordData",
    "ec2-instance-connect:SendSSHPublicKey",
    "ecr-public:GetAuthorizationToken",
    "ecr:GetAuthorizationToken",
    "gamelift:GetComputeAuthToken",
    "gamelift:GetGameSessionLogUrl",
    "gamelift:GetInstanceAccess",
    "gamelift:RequestUploadCredentials",
    "iam:CreateAccessKey",
    "iam:CreateLoginProfile",
    "iam:CreateServiceSpecificCredential",
    "iam:ResetServiceSpecificCredential",
    "iam:UpdateAccessKey",
    "lightsail:DownloadDefaultKeyPair",
    "lightsail:GetBucketAccessKeys",
    "lightsail:GetKeyPair",
    "lightsail:GetKeyPairs",
    "lightsail:GetRelationalDatabaseMasterUserPassword",
    "mediapackage:RotateChannelCredentials",
    "mediapackage:RotateIngestEndpointCredentials",
    "redshift:GetClusterCredentials",
    "s3:GetDataAccess",
    "snowball:GetJobUnlockCode",
    "storagegateway:DescribeChapCredentials",
    "sts:AssumeRole",
    "sts:AssumeRoleWithSAML",
    "sts:AssumeRoleWithWebIdentity",
    "sts:GetFederationToken",
    "sts:GetSessionToken",
    "waf-regional:GetChangeToken",
    "waf:GetChangeToken",
}

DATA_ACCESS_ACTIONS = {
    "appsync:GetDataSource",
    "appsync:GetFunction",
    "athena:GetQueryExecution",
    "athena:GetQueryResults",
    "cassandra:Select",
    "chatbot:DescribeSlackUserIdentities",
    "chatbot:ListMicrosoftTeamsConfiguredTeams",
    "chatbot:ListMicrosoftTeamsUserIdentities",
    "chime:GetAttendee",
    "chime:GetChannelMessage",
    "chime:GetMeeting",
    "chime:GetRoom",
    "chime:GetUser",
    "chime:GetUserSettings",
    "chime:ListAttendees",
    "chime:ListMeetings",
    "chime:ListUsers",
    "cleanrooms:GetProtectedQuery",
    "cloudformation:GetTemplate",
    "cloudfront:GetFunction",
    "cloudtrail:GetQueryResults",
    "cloudtrail:LookupEvents",
    "codeartifact:GetPackageVersionAsset",
    "codeartifact:GetPackageVersionReadme",
    "codebuild:BatchGetReportGroups",
    "codebuild:BatchGetReports",
    "codecommit:BatchGetCommits",
    "codecommit:BatchGetRepositories",
    "codecommit:DescribeMergeConflicts",
    "codecommit:DescribePullRequestEvents",
    "codecommit:GetApprovalRuleTemplate",
    "codecommit:GetBlob",
    "codecommit:GetBranch",
    "codecommit:GetComment",
    "codecommit:GetCommentReactions",
    "codecommit:GetCommentsForComparedCommit",
    "codecommit:GetCommentsForPullRequest",
    "codecommit:GetCommit",
    "codecommit:GetDifferences",
    "codecommit:GetFile",
    "codecommit:GetFolder",
    "codecommit:GetMergeCommit",
    "codecommit:GetMergeConflicts",
    "codecommit:GetMergeOptions",
    "codecommit:GetPullRequest",
    "codecommit:GetPullRequestApprovalStates",
    "codecommit:GetPullRequestOverrideState",
    "codeguru-profiler:GetRecommendations",
    "codeguru-reviewer:DescribeCodeReview",
    "codeguru-reviewer:DescribeRecommendationFeedback",
    "codepipeline:GetPipelineExecution",
    "cognito-identity:LookupDeveloperIdentity",
    "cognito-idp:AdminGetDevice",
    "cognito-idp:AdminGetUser",
    "cognito-idp:AdminListDevices",
    "cognito-idp:AdminListGroupsForUser",
    "cognito-idp:AdminListUserAuthEvents",
    "cognito-idp:GetDevice",
    "cognito-idp:GetGroup",
    "cognito-idp:GetUser",
    "cognito-idp:ListDevices",
    "cognito-idp:ListGroups",
    "cognito-idp:ListUsers",
    "cognito-sync:ListRecords",
    "connect:ListUsers",
    "datapipeline:QueryObjects",
    "dynamodb:BatchGetItem",
    "dynamodb:GetItem",
    "dynamodb:GetRecords",
    "dynamodb:Query",
    "dynamodb:Scan",
    "ecr:GetDownloadUrlForLayer",
    "gamelift:GetInstanceAccess",
    "kendra:Query",
    "kinesis:GetRecords",
    "kinesisvideo:GetImages",
    "kinesisvideo:GetMedia",
    "kms:CreateGrant",
    "lambda:GetFunction",
    "lambda:GetLayerVersion",
    "lightsail:GetContainerImages",
    "logs:GetLogEvents",
    "logs:GetLogRecord",
    "logs:GetQueryResults",
    "macie2:GetFindings",
    "mediastore:GetObject",
    "qldb:GetBlock",
    "rds:DownloadDBLogFilePortion",
    "robomaker:GetWorldTemplateBody",
    "s3:GetObject",
    "s3:GetObjectVersion",
    "sagemaker:Search",
    "sdb:Select",
    "serverlessrepo:GetApplication",
    "serverlessrepo:GetCloudFormationTemplate",
    "sqs:ReceiveMessage",
    "ssm:GetDocument",
    "ssm:GetParameter",
    "ssm:GetParameterHistory",
    "ssm:GetParameters",
    "ssm:GetParametersByPath",
    "support:DescribeAttachment",
    "support:DescribeCommunications",
    "wafv2:GetSampledRequests",
    "workdocs:GetDocument",
    "workdocs:GetDocumentPath",
    "workdocs:GetDocumentVersion",
    "workmail:ListGroupMembers",
    "workmail:ListGroups",
    "workmail:ListUsers",
}

PRIVESC_ACTIONS = {
    "codestar:AssociateTeamMember",
    "codestar:CreateProject",
    "ec2-instance-connect:SendSSHPublicKey",
    "glue:UpdateDevEndpoint",
    "iam:AddUserToGroup",
    "iam:AttachGroupPolicy",
    "iam:AttachRolePolicy",
    "iam:AttachUserPolicy",
    "iam:CreateAccessKey",
    "iam:CreateLoginProfile",
    "iam:CreatePolicyVersion",
    "iam:CreateServiceLinkedRole",
    "iam:CreateVirtualMFADevice",
    "iam:DeleteRolePermissionsBoundary",
    "iam:DeleteUserPermissionsBoundary",
    "iam:EnableMFADevice",
    "iam:PassRole",
    "iam:PutGroupPolicy",
    "iam:PutRolePermissionsBoundary",
    "iam:PutRolePolicy",
    "iam:PutUserPermissionsBoundary",
    "iam:PutUserPolicy",
    "iam:ResyncMFADevice",
    "iam:SetDefaultPolicyVersion",
    "iam:UpdateAssumeRolePolicy",
    "iam:UpdateLoginProfile",
    "kms:CreateGrant",
}

RESOURCE_EXPOSURE_ACTIONS = {
    "acm-pca:CreatePermission",
    "acm-pca:DeletePermission",
    "acm-pca:DeletePolicy",
    "acm-pca:PutPolicy",
    "backup:DeleteBackupVaultAccessPolicy",
    "backup:PutBackupVaultAccessPolicy",
    "chime:DeleteVoiceConnectorTerminationCredentials",
    "chime:PutVoiceConnectorTerminationCredentials",
    "cloudformation:SetStackPolicy",
    "cloudsearch:UpdateServiceAccessPolicies",
    "codeartifact:DeleteDomainPermissionsPolicy",
    "codeartifact:DeleteRepositoryPermissionsPolicy",
    "codebuild:DeleteResourcePolicy",
    "codebuild:DeleteSourceCredentials",
    "codebuild:ImportSourceCredentials",
    "codebuild:PutResourcePolicy",
    "codeguru-profiler:PutPermission",
    "codeguru-profiler:RemovePermission",
    "codestar:AssociateTeamMember",
    "codestar:CreateProject",
    "codestar:DeleteProject",
    "codestar:DisassociateTeamMember",
    "codestar:UpdateTeamMember",
    "cognito-identity:CreateIdentityPool",
    "cognito-identity:DeleteIdentities",
    "cognito-identity:DeleteIdentityPool",
    "cognito-identity:GetId",
    "cognito-identity:MergeDeveloperIdentities",
    "cognito-identity:SetIdentityPoolRoles",
    "cognito-identity:UnlinkDeveloperIdentity",
    "cognito-identity:UnlinkIdentity",
    "cognito-identity:UpdateIdentityPool",
    "ds:CreateConditionalForwarder",
    "ds:CreateDirectory",
    "ds:CreateMicrosoftAD",
    "ds:CreateTrust",
    "ds:ShareDirectory",
    "ec2:CreateNetworkInterfacePermission",
    "ec2:DeleteNetworkInterfacePermission",
    "ec2:DisableImageBlockPublicAccess",
    "ec2:ModifySnapshotAttribute",
    "ec2:ModifyVpcEndpointServicePermissions",
    "ec2:ResetSnapshotAttribute",
    "ecr:DeleteRepositoryPolicy",
    "ecr:SetRepositoryPolicy",
    "elasticfilesystem:DeleteFileSystemPolicy",
    "elasticfilesystem:PutFileSystemPolicy",
    "elasticmapreduce:PutBlockPublicAccessConfiguration",
    "es:CreateElasticsearchDomain",
    "es:UpdateElasticsearchDomainConfig",
    "glacier:AbortVaultLock",
    "glacier:CompleteVaultLock",
    "glacier:DeleteVaultAccessPolicy",
    "glacier:InitiateVaultLock",
    "glacier:SetDataRetrievalPolicy",
    "glacier:SetVaultAccessPolicy",
    "glue:DeleteResourcePolicy",
    "glue:PutResourcePolicy",
    "greengrass:AssociateServiceRoleToAccount",
    "health:DisableHealthServiceAccessForOrganization",
    "health:EnableHealthServiceAccessForOrganization",
    "iam:AddClientIDToOpenIDConnectProvider",
    "iam:AddRoleToInstanceProfile",
    "iam:AddUserToGroup",
    "iam:AttachGroupPolicy",
    "iam:AttachRolePolicy",
    "iam:AttachUserPolicy",
    "iam:ChangePassword",
    "iam:CreateAccessKey",
    "iam:CreateAccountAlias",
    "iam:CreateGroup",
    "iam:CreateInstanceProfile",
    "iam:CreateLoginProfile",
    "iam:CreateOpenIDConnectProvider",
    "iam:CreatePolicy",
    "iam:CreatePolicyVersion",
    "iam:CreateRole",
    "iam:CreateSAMLProvider",
    "iam:CreateServiceLinkedRole",
    "iam:CreateServiceSpecificCredential",
    "iam:CreateUser",
    "iam:CreateVirtualMFADevice",
    "iam:DeactivateMFADevice",
    "iam:DeleteAccessKey",
    "iam:DeleteAccountAlias",
    "iam:DeleteAccountPasswordPolicy",
    "iam:DeleteGroup",
    "iam:DeleteGroupPolicy",
    "iam:DeleteInstanceProfile",
    "iam:DeleteLoginProfile",
    "iam:DeleteOpenIDConnectProvider",
    "iam:DeletePolicy",
    "iam:DeletePolicyVersion",
    "iam:DeleteRole",
    "iam:DeleteRolePermissionsBoundary",
    "iam:DeleteRolePolicy",
    "iam:DeleteSAMLProvider",
    "iam:DeleteServerCertificate",
    "iam:DeleteServiceLinkedRole",
    "iam:DeleteServiceSpecificCredential",
    "iam:DeleteSigningCertificate",
    "iam:DeleteSSHPublicKey",
    "iam:DeleteUser",
    "iam:DeleteUserPermissionsBoundary",
    "iam:DeleteUserPolicy",
    "iam:DeleteVirtualMFADevice",
    "iam:DetachGroupPolicy",
    "iam:DetachRolePolicy",
    "iam:DetachUserPolicy",
    "iam:EnableMFADevice",
    "iam:PassRole",
    "iam:PutGroupPolicy",
    "iam:PutRolePermissionsBoundary",
    "iam:PutRolePolicy",
    "iam:PutUserPermissionsBoundary",
    "iam:PutUserPolicy",
    "iam:RemoveClientIDFromOpenIDConnectProvider",
    "iam:RemoveRoleFromInstanceProfile",
    "iam:RemoveUserFromGroup",
    "iam:ResetServiceSpecificCredential",
    "iam:ResyncMFADevice",
    "iam:SetDefaultPolicyVersion",
    "iam:SetSecurityTokenServicePreferences",
    "iam:UpdateAccessKey",
    "iam:UpdateAccountPasswordPolicy",
    "iam:UpdateAssumeRolePolicy",
    "iam:UpdateGroup",
    "iam:UpdateLoginProfile",
    "iam:UpdateOpenIDConnectProviderThumbprint",
    "iam:UpdateRole",
    "iam:UpdateRoleDescription",
    "iam:UpdateSAMLProvider",
    "iam:UpdateServerCertificate",
    "iam:UpdateServiceSpecificCredential",
    "iam:UpdateSigningCertificate",
    "iam:UpdateSSHPublicKey",
    "iam:UpdateUser",
    "iam:UploadServerCertificate",
    "iam:UploadSigningCertificate",
    "iam:UploadSSHPublicKey",
    "imagebuilder:PutComponentPolicy",
    "imagebuilder:PutImagePolicy",
    "imagebuilder:PutImageRecipePolicy",
    "iot:AttachPolicy",
    "iot:AttachPrincipalPolicy",
    "iot:DetachPolicy",
    "iot:DetachPrincipalPolicy",
    "iot:SetDefaultAuthorizer",
    "iot:SetDefaultPolicyVersion",
    "iotsitewise:CreateAccessPolicy",
    "iotsitewise:DeleteAccessPolicy",
    "iotsitewise:UpdateAccessPolicy",
    "kms:CreateGrant",
    "kms:PutKeyPolicy",
    "kms:RetireGrant",
    "kms:RevokeGrant",
    "lakeformation:BatchGrantPermissions",
    "lakeformation:BatchRevokePermissions",
    "lakeformation:GrantPermissions",
    "lakeformation:PutDataLakeSettings",
    "lakeformation:RevokePermissions",
    "lambda:AddLayerVersionPermission",
    "lambda:AddPermission",
    "lambda:RemoveLayerVersionPermission",
    "lambda:RemovePermission",
    "license-manager:UpdateServiceSettings",
    "lightsail:GetRelationalDatabaseMasterUserPassword",
    "logs:DeleteResourcePolicy",
    "logs:PutResourcePolicy",
    "mediapackage:RotateIngestEndpointCredentials",
    "mediastore:DeleteContainerPolicy",
    "mediastore:PutContainerPolicy",
    "opsworks:SetPermission",
    "opsworks:UpdateUserProfile",
    "quicksight:CreateGroup",
    "quicksight:CreateGroupMembership",
    "quicksight:CreateIAMPolicyAssignment",
    "quicksight:DeleteGroup",
    "quicksight:DeleteGroupMembership",
    "quicksight:DeleteIAMPolicyAssignment",
    "quicksight:DeleteUser",
    "quicksight:DeleteUserByPrincipalId",
    "quicksight:RegisterUser",
    "quicksight:UpdateDashboardPermissions",
    "quicksight:UpdateGroup",
    "quicksight:UpdateIAMPolicyAssignment",
    "quicksight:UpdateTemplatePermissions",
    "quicksight:UpdateUser",
    "ram:AcceptResourceShareInvitation",
    "ram:AssociateResourceShare",
    "ram:CreateResourceShare",
    "ram:DeleteResourceShare",
    "ram:DisassociateResourceShare",
    "ram:EnableSharingWithAwsOrganization",
    "ram:RejectResourceShareInvitation",
    "ram:UpdateResourceShare",
    "rds:AuthorizeDBSecurityGroupIngress",
    "redshift:AuthorizeSnapshotAccess",
    "redshift:CreateSnapshotCopyGrant",
    "redshift:ModifyClusterIamRoles",
    "redshift:RevokeSnapshotAccess",
    "route53resolver:PutResolverRulePolicy",
    "s3:DeleteBucketPolicy",
    "s3:PutAccessPointPolicy",
    "s3:PutAccountPublicAccessBlock",
    "s3:PutBucketAcl",
    "s3:PutBucketPolicy",
    "s3:PutBucketPublicAccessBlock",
    "s3:PutObjectAcl",
    "secretsmanager:DeleteResourcePolicy",
    "secretsmanager:PutResourcePolicy",
    "secretsmanager:ValidateResourcePolicy",
    "servicecatalog:CreatePortfolioShare",
    "servicecatalog:DeletePortfolioShare",
    "sns:AddPermission",
    "sns:CreateTopic",
    "sns:RemovePermission",
    "sns:SetTopicAttributes",
    "sqs:AddPermission",
    "sqs:CreateQueue",
    "sqs:RemovePermission",
    "sqs:SetQueueAttributes",
    "ssm:ModifyDocumentPermission",
    "sso:CreatePermissionSet",
    "sso:DeletePermissionSet",
    "sso:UpdatePermissionSet",
    "storagegateway:DeleteChapCredentials",
    "storagegateway:SetLocalConsolePassword",
    "storagegateway:SetSMBGuestPassword",
    "storagegateway:UpdateChapCredentials",
    "waf-regional:DeletePermissionPolicy",
    "waf-regional:PutPermissionPolicy",
    "waf:DeletePermissionPolicy",
    "waf:PutPermissionPolicy",
    "wafv2:CreateWebACL",
    "wafv2:DeletePermissionPolicy",
    "wafv2:DeleteWebACL",
    "wafv2:PutPermissionPolicy",
    "wafv2:UpdateWebACL",
    "worklink:UpdateDevicePolicyConfiguration",
    "workmail:ResetPassword",
    "xray:PutEncryptionConfig",
}

CLOUDTRAIL_SERVICE_MAPPINGS = {
    "access-analyzer.amazonaws.com": "access-analyzer",
    "acm-pca.amazonaws.com": "acm-pca",
    "acm.amazonaws.com": "acm",
    "apigateway.amazonaws.com": "apigateway",
    "appconfig.amazonaws.com": "appconfig",
    "appflow.amazonaws.com": "appflow",
    "appmesh.amazonaws.com": "appmesh",
    "apprunner.amazonaws.com": "apprunner",
    "appstream.amazonaws.com": "appstream",
    "appsync.amazonaws.com": "appsync",
    "athena.amazonaws.com": "athena",
    "autoscaling.amazonaws.com": "autoscaling",
    "backup.amazonaws.com": "backup",
    "batch.amazonaws.com": "batch",
    "bedrock.amazonaws.com": "bedrock",
    "cassandra.amazonaws.com": "cassandra",
    "ce.amazonaws.com": "ce",
    "chatbot.amazonaws.com": "chatbot",
    "chime.amazonaws.com": "chime",
    "cleanrooms.amazonaws.com": "cleanrooms",
    "cloud9.amazonaws.com": "cloud9",
    "cloudformation.amazonaws.com": "cloudformation",
    "cloudfront.amazonaws.com": "cloudfront",
    "cloudhsm.amazonaws.com": "cloudhsm",
    "cloudhsmv2.amazonaws.com": "cloudhsmv2",
    "cloudsearch.amazonaws.com": "cloudsearch",
    "cloudtrail.amazonaws.com": "cloudtrail",
    "cloudwatch.amazonaws.com": "cloudwatch",
    "codeartifact.amazonaws.com": "codeartifact",
    "codebuild.amazonaws.com": "codebuild",
    "codecommit.amazonaws.com": "codecommit",
    "codedeploy.amazonaws.com": "codedeploy",
    "codeguru-profiler.amazonaws.com": "codeguru-profiler",
    "codeguru-reviewer.amazonaws.com": "codeguru-reviewer",
    "codepipeline.amazonaws.com": "codepipeline",
    "codestar.amazonaws.com": "codestar",
    "cognito-identity.amazonaws.com": "cognito-identity",
    "cognito-idp.amazonaws.com": "cognito-idp",
    "cognito-sync.amazonaws.com": "cognito-sync",
    "comprehend.amazonaws.com": "comprehend",
    "config.amazonaws.com": "config",
    "connect.amazonaws.com": "connect",
    "datapipeline.amazonaws.com": "datapipeline",
    "datasync.amazonaws.com": "datasync",
    "dax.amazonaws.com": "dax",
    "directconnect.amazonaws.com": "directconnect",
    "discovery.amazonaws.com": "discovery",
    "dlm.amazonaws.com": "dlm",
    "dms.amazonaws.com": "dms",
    "ds.amazonaws.com": "ds",
    "dynamodb.amazonaws.com": "dynamodb",
    "ec2.amazonaws.com": "ec2",
    "ec2-instance-connect.amazonaws.com": "ec2-instance-connect",
    "ecr.amazonaws.com": "ecr",
    "ecr-public.amazonaws.com": "ecr-public",
    "ecs.amazonaws.com": "ecs",
    "eks.amazonaws.com": "eks",
    "elasticache.amazonaws.com": "elasticache",
    "elasticbeanstalk.amazonaws.com": "elasticbeanstalk",
    "elasticfilesystem.amazonaws.com": "elasticfilesystem",
    "elasticloadbalancing.amazonaws.com": "elasticloadbalancing",
    "elasticmapreduce.amazonaws.com": "elasticmapreduce",
    "elastictranscoder.amazonaws.com": "elastictranscoder",
    "es.amazonaws.com": "es",
    "events.amazonaws.com": "events",
    "firehose.amazonaws.com": "firehose",
    "fms.amazonaws.com": "fms",
    "forecast.amazonaws.com": "forecast",
    "fsx.amazonaws.com": "fsx",
    "gamelift.amazonaws.com": "gamelift",
    "glacier.amazonaws.com": "glacier",
    "globalaccelerator.amazonaws.com": "globalaccelerator",
    "glue.amazonaws.com": "glue",
    "greengrass.amazonaws.com": "greengrass",
    "groundstation.amazonaws.com": "groundstation",
    "guardduty.amazonaws.com": "guardduty",
    "health.amazonaws.com": "health",
    "iam.amazonaws.com": "iam",
    "imagebuilder.amazonaws.com": "imagebuilder",
    "inspector.amazonaws.com": "inspector",
    "inspector2.amazonaws.com": "inspector2",
    "iot.amazonaws.com": "iot",
    "iot1click.amazonaws.com": "iot1click",
    "iotanalytics.amazonaws.com": "iotanalytics",
    "iotevents.amazonaws.com": "iotevents",
    "iotsitewise.amazonaws.com": "iotsitewise",
    "kafka.amazonaws.com": "kafka",
    "kendra.amazonaws.com": "kendra",
    "kinesis.amazonaws.com": "kinesis",
    "kinesisanalytics.amazonaws.com": "kinesisanalytics",
    "kinesisvideo.amazonaws.com": "kinesisvideo",
    "kms.amazonaws.com": "kms",
    "lakeformation.amazonaws.com": "lakeformation",
    "lambda.amazonaws.com": "lambda",
    "lex.amazonaws.com": "lex",
    "license-manager.amazonaws.com": "license-manager",
    "lightsail.amazonaws.com": "lightsail",
    "logs.amazonaws.com": "logs",
    "machinelearning.amazonaws.com": "machinelearning",
    "macie2.amazonaws.com": "macie2",
    "managedblockchain.amazonaws.com": "managedblockchain",
    "mediaconnect.amazonaws.com": "mediaconnect",
    "mediaconvert.amazonaws.com": "mediaconvert",
    "medialive.amazonaws.com": "medialive",
    "mediapackage.amazonaws.com": "mediapackage",
    "mediastore.amazonaws.com": "mediastore",
    "mediatailor.amazonaws.com": "mediatailor",
    "memorydb.amazonaws.com": "memorydb",
    "mgh.amazonaws.com": "mgh",
    "mgn.amazonaws.com": "mgn",
    "mobiletargeting.amazonaws.com": "mobiletargeting",
    "mq.amazonaws.com": "mq",
    "neptune.amazonaws.com": "neptune",
    "networkfirewall.amazonaws.com": "network-firewall",
    "networkmanager.amazonaws.com": "networkmanager",
    "nimble.amazonaws.com": "nimble",
    "opsworks.amazonaws.com": "opsworks",
    "organizations.amazonaws.com": "organizations",
    "outposts.amazonaws.com": "outposts",
    "personalize.amazonaws.com": "personalize",
    "pinpoint.amazonaws.com": "mobiletargeting",
    "polly.amazonaws.com": "polly",
    "qldb.amazonaws.com": "qldb",
    "quicksight.amazonaws.com": "quicksight",
    "ram.amazonaws.com": "ram",
    "rds.amazonaws.com": "rds",
    "redshift.amazonaws.com": "redshift",
    "rekognition.amazonaws.com": "rekognition",
    "resiliencehub.amazonaws.com": "resiliencehub",
    "resource-groups.amazonaws.com": "resource-groups",
    "robomaker.amazonaws.com": "robomaker",
    "route53.amazonaws.com": "route53",
    "route53domains.amazonaws.com": "route53domains",
    "route53resolver.amazonaws.com": "route53resolver",
    "s3.amazonaws.com": "s3",
    "sagemaker.amazonaws.com": "sagemaker",
    "sdb.amazonaws.com": "sdb",
    "secretsmanager.amazonaws.com": "secretsmanager",
    "securityhub.amazonaws.com": "securityhub",
    "serverlessrepo.amazonaws.com": "serverlessrepo",
    "servicecatalog.amazonaws.com": "servicecatalog",
    "servicediscovery.amazonaws.com": "servicediscovery",
    "servicequotas.amazonaws.com": "servicequotas",
    "ses.amazonaws.com": "ses",
    "sesv2.amazonaws.com": "ses",
    "shield.amazonaws.com": "shield",
    "signer.amazonaws.com": "signer",
    "signin.amazonaws.com": "signin",
    "snowball.amazonaws.com": "snowball",
    "sns.amazonaws.com": "sns",
    "sqs.amazonaws.com": "sqs",
    "ssm.amazonaws.com": "ssm",
    "ssm-contacts.amazonaws.com": "ssm-contacts",
    "ssm-incidents.amazonaws.com": "ssm-incidents",
    "sso.amazonaws.com": "sso",
    "sso-directory.amazonaws.com": "sso-directory",
    "states.amazonaws.com": "states",
    "storagegateway.amazonaws.com": "storagegateway",
    "sts.amazonaws.com": "sts",
    "support.amazonaws.com": "support",
    "swf.amazonaws.com": "swf",
    "synthetics.amazonaws.com": "synthetics",
    "textract.amazonaws.com": "textract",
    "timestream.amazonaws.com": "timestream",
    "transcribe.amazonaws.com": "transcribe",
    "transfer.amazonaws.com": "transfer",
    "translate.amazonaws.com": "translate",
    "trustedadvisor.amazonaws.com": "trustedadvisor",
    "waf-regional.amazonaws.com": "waf-regional",
    "waf.amazonaws.com": "waf",
    "wafv2.amazonaws.com": "wafv2",
    "wellarchitected.amazonaws.com": "wellarchitected",
    "workdocs.amazonaws.com": "workdocs",
    "worklink.amazonaws.com": "worklink",
    "workmail.amazonaws.com": "workmail",
    "workspaces.amazonaws.com": "workspaces",
    "xray.amazonaws.com": "xray",
}


def get_event_name(event):
    return event.get("eventName", "")


def get_event_source(event):
    return event.get("eventSource", "")


def get_iam_namespace(event):
    source = get_event_source(event)
    return CLOUDTRAIL_SERVICE_MAPPINGS.get(source, source.replace(".amazonaws.com", ""))


def get_action(event):
    namespace = get_iam_namespace(event)
    name = get_event_name(event)
    return f"{namespace}:{name}"


def is_credential_exposure(event):
    return get_action(event) in CREDENTIAL_EXPOSURE_ACTIONS


def is_privesc(event):
    return get_action(event) in PRIVESC_ACTIONS


def is_resource_exposure(event):
    return get_action(event) in RESOURCE_EXPOSURE_ACTIONS


def is_data_access(event):
    return get_action(event) in DATA_ACCESS_ACTIONS


def get_action_categories(event):
    action = get_action(event)
    categories = []
    if action in CREDENTIAL_EXPOSURE_ACTIONS:
        categories.append("CredentialExposure")
    if action in DATA_ACCESS_ACTIONS:
        categories.append("DataAccess")
    if action in PRIVESC_ACTIONS:
        categories.append("PrivEsc")
    if action in RESOURCE_EXPOSURE_ACTIONS:
        categories.append("ResourceExposure")
    return categories
